Switch to jetbrains-ide eclass

diff --git a/_util/templates/idea-ultimate-bin.ebuild.in b/_util/templates/idea-ultimate-bin.ebuild.in
--- a/_util/templates/idea-ultimate-bin.ebuild.in
+++ b/_util/templates/idea-ultimate-bin.ebuild.in
@@ -2,7 +2,7 @@
 # Distributed under the terms of the GNU General Public License v2
 
 EAPI=7
-inherit desktop
+inherit jetbrains-ide
 
 DESCRIPTION="Intelligent Java IDE"
 HOMEPAGE="https://www.jetbrains.com/idea/"
@@ -13,51 +13,15 @@ SLOT="0"
 KEYWORDS="~amd64"
 IUSE=""
 
-DEPEND=""
-RDEPEND="${DEPEND}
-	dev-java/jetbrains-jre-bin
-	dev-java/jansi-native
-	dev-libs/libdbusmenu"
 BDEPEND="dev-util/patchelf"
 
-RESTRICT="strip splitdebug mirror"
-
-src_unpack() {
-	default_src_unpack
-
-	mv idea-IU* "${P}"
-}
+IDE_FULL_NAME="IntelliJ IDEA Ultimate"
+IDE_BIN_NAME="idea"
+IDE_DIST_NAME="idea-IU"
+IDE_DIST_VERSION="any"
 
 src_prepare() {
-	rm -vf "${S}"/plugins/maven/lib/maven3/lib/jansi-native/*/libjansi*
-	rm -vrf "${S}"/lib/pty4j-native/linux/ppc64le
-	rm -vf "${S}"/bin/libdbm64*
+	patchelf --replace-needed liblldb.so.9 liblldb.so "${S}"/plugins/Kotlin/bin/linux/LLDBFrontend || die "Unable to patch LLDBFrontend for lldb"
 
-	patchelf --replace-needed liblldb.so liblldb.so.9 "${S}"/plugins/Kotlin/bin/linux/LLDBFrontend || die "Unable to patch LLDBFrontend for lldb"
-
-	sed -i \
-		-e "\$a\\\\" \
-		-e "\$a#-----------------------------------------------------------------------" \
-		-e "\$a# Disable automatic updates as these are handled through Gentoo's" \
-		-e "\$a# package manager. See bug #704494" \
-		-e "\$a#-----------------------------------------------------------------------" \
-		-e "\$aide.no.platform.update=Gentoo"  bin/idea.properties
-
-	eapply_user
-}
-
-src_install() {
-	local dir="/opt/${P}"
-
-	insinto "${dir}"
-	doins -r *
-	fperms 755 "${dir}"/bin/{format.sh,idea.sh,inspect.sh,printenv.py,restart.py,fsnotifier{,64}}
-
-	dosym "${dir}/bin/idea.sh" "/usr/bin/${PN}"
-	dosym "${dir}/bin/idea.png" "/usr/share/pixmaps/${PN}.png"
-	make_desktop_entry "${PN}" "IntelliJ IDEA" "${PN}" "Development;IDE;" "StartupWMClass=jetbrains-idea"
-
-	# recommended by: https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit
-	mkdir -p "${D}/etc/sysctl.d/" || die
-	echo "fs.inotify.max_user_watches = 524288" > "${D}/etc/sysctl.d/30-idea-inotify-watches.conf" || die
+	jetbrains-ide_src_prepare
 }
